INSERT INTO INSTRUMENT_PRICE_MODIFIER (id, name, multiplier) VALUES (1, 'INSTRUMENT1', 1.2304);
INSERT INTO INSTRUMENT_PRICE_MODIFIER (id, name, multiplier) VALUES (2, 'INSTRUMENT2', 20.97435);
INSERT INTO INSTRUMENT_PRICE_MODIFIER (id, name, multiplier) VALUES (3, 'INSTRUMENT3', 3.14);
